1. Create a null vector of size 10 but the fifth value which is 1 
2. Create a vector with values ranging from 10 to 49
3. Reverse a vector
4. Create a 3x3 matrix with values ranging from 0 to 8
5. Find indices of non-zero elements from [1,2,0,0,4,0]
6. Create a 3x3x3 array with random values
7. Create a 10x10 array with random values and find the minimum and maximum values
8. Create a 2d array with 1 on the border and 0 inside


In [3]:
import numpy as np
n1=np.zeros(10)
n1[4]=1
n1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [4]:
n2=np.array(range(10,50))
n2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
np.flip(n2)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
n4=np.array(range(0,9)).reshape(3,3)
n4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
n5=np.array([1,2,0,0,4,0])
np.where(n5==0)

(array([2, 3, 5]),)

In [22]:
# Create a 3x3x3 array with random values
n6=np.random.rand(2,3,4)
n6

array([[[0.33672934, 0.74347083, 0.82711903, 0.76230431],
        [0.46339631, 0.43534839, 0.57825164, 0.1639233 ],
        [0.5954738 , 0.90282421, 0.19723324, 0.16778714]],

       [[0.87838721, 0.89277809, 0.20601199, 0.50027773],
        [0.15937621, 0.12715979, 0.94457357, 0.57296539],
        [0.19144348, 0.56445727, 0.40036908, 0.92502894]]])

In [26]:
n6=np.random.randint(80,size=(3,3,3))
n6

array([[[ 3, 69,  7],
        [25, 51, 15],
        [51, 45, 37]],

       [[ 7, 67, 10],
        [53,  0, 64],
        [15, 76, 14]],

       [[77,  5, 33],
        [53,  0,  9],
        [35, 17, 73]]])

In [31]:
# Create a 10x10 array with random values and find the minimum and maximum values
n7=np.random.randint(121,size=(10,10))
n7.min(),n7.max()

(0, 120)

In [87]:
# Create a 2d array with 1 on the border and 0 inside
n8=np.ones((4,4))
n8[1:-1,1:-1]=0
n8

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

3